name: simple
description: "Where the superfluous go to die."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  cached_network_image: ^3.1.0
  solana: ^0.30.4
  intl: ^0.19.0
  solana_wallet_adapter: ^0.1.5
  android_intent_plus: ^5.0.2
  flutter_localization: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_white_background.png
    - assets/jup_icon.png
