publisher:
  name: Pseudonymous Developer
  address: 5hTcgxmxYJsWn6n3MWxKuWB482GW9fJxoa7GYWhZ7sjc
  website: https://simple-solana-app.github.io/
  email: simplesolanaapp@gmail.com
  media:
    - purpose: icon
      uri: ./media/512x512_logo.png
app:
  name: simple
  address: 9C5FhWjjhH5G3RcM2V9VFCDDTQ9vnu1EthE8HmXJe14H
  android_package: simple.solana.app
  urls:
    license_url: https://github.com/simple-solana-app/simple/blob/master/LICENSE
    copyright_url: https://github.com/simple-solana-app/simple/blob/master/LICENSE
    privacy_policy_url: https://github.com/simple-solana-app/simple/blob/master/PRIVACY_POLICY.md
    website: https://simple-solana-app.github.io/
  media:
    - purpose: icon
      uri: ./media/512x512_logo.png
release:
  address: CjCF7LzoRNmS8xCChuRvBixwNWqecPMXKmsmJt29Zfrf
  media:
    - purpose: icon
      uri: ./media/512x512_logo.png
    - purpose: screenshot
      uri: ./media/tokens_page.png
    - purpose: screenshot
      uri: ./media/portfolio_page.png
    - purpose: screenshot
      uri: ./media/token_price_with_graph.png
    - purpose: screenshot
      uri: ./media/token_info.png
  files:
    - purpose: install
      uri: ./files/app-release.apk
  catalog:
    en-US:
      name: simple
      short_description: It's ◎h s◎ simple!
      long_description: Where the superfluous go to die.
      new_in_version: Code optimizations and interactivity with the protocol.
      saga_features: App is exclusively available on the dApp Store.
solana_mobile_dapp_publisher_portal:
  google_store_package: simple.solana.app
  testing_instructions: Nothing specific comes to mind
lastSubmittedVersionOnChain:
  address: CjCF7LzoRNmS8xCChuRvBixwNWqecPMXKmsmJt29Zfrf
  version_code: 2
  apk_hash: wSlSOjJ2gUIfYC5cnfgTIZhhStF9x26qXjCQKMu/o7E=
lastUpdatedVersionOnStore:
  address: CjCF7LzoRNmS8xCChuRvBixwNWqecPMXKmsmJt29Zfrf
